### ISSUE TITLE
exists

### ISSUE THREAD

**Issue by tinovyatkin** [bdistin/fs-nextra#35]
Hello,

It seems that `exists` is not in `fs/promises` in Node 10, so, must be manually checked and added as promisified version...

**Comment by bdistin** [comment]
fs.exists is Deprecated:
>Stability: 0 - Deprecated This feature is known to be problematic, and changes may be planned. Do not rely on it. Use of the feature may cause warnings to be emitted. Backwards compatibility across major versions should not be expected.

Which is why it wasn't added to fs/promises. Node recommends using stat() or access() instead. fs-nextra implements pathExists() using the recommended access() method: https://github.com/bdistin/fs-nextra/blob/master/src/nextra/pathExists.js#L11

pathExists() is functionally identical to the former promisified fs.exists() as you can see via the callback version node impliments: https://github.com/nodejs/node/blob/master/lib/fs.js#L203-L215
